# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deployment
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
